# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
spotless = "8.1.0"
version-catalog-update = "1.0.1"
spring-boot = "4.0.1"
postgresql = "42.7.8"
flyway = "11.20.0"
lombok = "1.18.42"
mapstruct = "1.6.3"
hibernate = "7.0.3.Final"
jobrunr = "7.4.1"
jackson2 = "2.18.2"
azure-communication-services = "1.0.0"
opentelemetry-logback-appender = "2.23.0-alpha"
datasource-micrometer-spring-boot = "2.0.1"
jwt-lib = "1.0.0-SNAPSHOT"
denovm-lib = "1.0.0-SNAPSHOT"
flow-lib = "1.0.0-SNAPSHOT"
springdoc = "2.8.4"
caffeine = "3.1.8"
json-logic = "1.0.9"

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }

[libraries]
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-aspectj = { module = "org.springframework.boot:spring-boot-starter-aspectj" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
spring-boot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-opentelemetry = { module = "org.springframework.boot:spring-boot-starter-opentelemetry" }
opentelemetry-logback-appender = { module = "io.opentelemetry.instrumentation:opentelemetry-logback-appender-1.0", version.ref = "opentelemetry-logback-appender" }
datasource-micrometer-spring-boot = { module = "net.ttddyy.observation:datasource-micrometer-spring-boot", version.ref = "datasource-micrometer-spring-boot" }
spring-data-commons = { module = "org.springframework.data:spring-data-commons" }
aspectjrt = { module = "org.aspectj:aspectjrt" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
hibernate-envers = { module = "org.hibernate.orm:hibernate-envers", version.ref = "hibernate" }
jackson-databind = { module = "tools.jackson.core:jackson-databind" }
jackson2-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson2" }
jackson2-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson2" }
jobrunr-spring-boot-starter = { module = "org.jobrunr:jobrunr-spring-boot-3-starter", version.ref = "jobrunr" }
azure-communication-services-email = { group = "com.azure", name = "azure-communication-email", version.ref = "azure-communication-services" }
denovm = { group = "com.fynxt", name = "denovm", version.ref = "denovm-lib" }
flow = { group = "com.fynxt", name = "lowcode-flow", version.ref = "flow-lib" }
jwt = { group = "com.fynxt", name = "jwt", version.ref = "jwt-lib" }
springdoc-openapi-starter-webmvc-ui = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
json-logic = { module = "io.github.jamsesso:json-logic-java", version.ref = "json-logic" }

[bundles]
caching = ["caffeine"]