# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
spotless = "8.1.0"
version-catalog-update = "1.0.1"
spring-boot = "4.0.1"
postgresql = "42.7.8"
flyway = "11.20.0"
lombok = "1.18.42"
mapstruct = "1.6.3"
hibernate = "7.0.3.Final"
jobrunr = "7.4.1"
jackson2 = "2.18.2"
azure-communication-services = "1.0.0"

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }

[libraries]
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-data-commons = { module = "org.springframework.data:spring-data-commons" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
hibernate-envers = { module = "org.hibernate.orm:hibernate-envers", version.ref = "hibernate" }
jackson-databind = { module = "tools.jackson.core:jackson-databind" }
jackson2-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson2" }
jobrunr-spring-boot-starter = { module = "org.jobrunr:jobrunr-spring-boot-3-starter", version.ref = "jobrunr" }
azure-communication-services-email = { group = "com.azure", name = "azure-communication-email", version.ref = "azure-communication-services" }