# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
spotless = "8.1.0"
version-catalog-update = "1.0.1"

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
