# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
spotless = "8.1.0"
version-catalog-update = "1.0.1"
spring-boot = "4.0.1"
postgresql = "42.7.8"
flyway = "11.20.0"

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }

[libraries]
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
